name: practice_1
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
      - name: Deploy
        run: echo "Deploying..."
